version: "3"

services:
  trino:
    image: trinodb/trino
    container_name: trino
    networks:
      data-lake-network:
    ports:
      - 8080:8080
    volumes:
      - "./trino/trino_connections/postgres.properties:/etc/trino/catalog/postgres.properties"
      - "./trino/trino_connections/mariadb.properties:/etc/trino/catalog/mariadb.properties"
      - "./trino/coordinator-config-ci.properties:/etc/trino/config.properties"

  postgres:
    image: postgres:15
    container_name: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      data-lake-network:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  mariadb:
    image: mariadb:10.5
    restart: always
    networks:
      data-lake-network:
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'

networks:
  data-lake-network: 
