PostgresDbt:
  outputs:
    dev:
      database: postgres
      host: localhost
      port: 5432
      schema: dbt_models
      threads: 1
      type: postgres
      user: postgres
      password: postgres
  target: dev