PostgresDbt:
  outputs:
    dev:
      database: postgres
      host: localhost
      port: 5432
      schema: dev_test
      threads: 1
      type: postgres
      user: postgres
      password: postgres

    container:
      database: postgres
      host: postgres
      port: 5432
      schema: dev_test
      threads: 1
      type: postgres
      user: postgres
      password: postgres
  target: dev