PostgresDbt:
  outputs:
    dev:
      database: postgres
      host: localhost
      port: 5432
      schema: "{{ env_var('DBT_SCHEMA', 'dev_test') }}"
      threads: 1
      type: postgres
      user: postgres
      password: postgres

    container:
      database: postgres
      host: postgres
      port: 5432
      schema: "{{ env_var('DBT_SCHEMA', 'dev_test') }}"
      threads: 1
      type: postgres
      user: postgres
      password: postgres
  target: dev