TrinoIngestionDbt:
  outputs:
    dev:
      database: postgres
      host: localhost
      method: none
      port: 8080
      schema: dbt
      threads: 1
      type: trino
      user: admin
  target: dev