TrinoIngestionDbt:
  outputs:
    dev:
      database: postgres
      host: localhost
      method: none
      port: 8080
      schema: dev_test
      threads: 1
      type: trino
      user: admin

    container:
      database: postgres
      host: trino
      method: none
      port: 8080
      schema: dev_test
      threads: 1
      type: trino
      user: admin
  target: dev