name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      postgres_changed: ${{ steps.filter.outputs.postgres == 'true' }}
      trino_changed: ${{ steps.filter.outputs.trino == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Paths filter
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            postgres:
              - 'dbt/PostgresDbt/**'
            trino:
              - 'dbt/TrinoIngestionDbt/**'

  run-on-trino-changed:
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.trino_changed == 'true'
    steps:
      - name: Echo Trino Change
        run: echo "Files in Trino were changed!"

  run-on-postgres-changed:
    runs-on: ubuntu-latest
    needs:
      - filter
      - run-on-trino-changed
    if: >
      needs.filter.outputs.postgres_changed == 'true' &&
      (needs['run-on-trino-changed'].result == 'success' || needs['run-on-trino-changed'].result == 'skipped')
    steps:
      - name: Echo Postgres Change
        run: echo "Files in Postgres were changed!"

